# Basic Python

## 1. Split this string

In [32]:
s = "Hi there Sam!"
x=s.split()
print(x)


['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [33]:
str=("This diameter of {planet} is {diameter} kilometers")
print((str.format(planet = "Earth",
diameter = 12742)))


This diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [34]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d.get('target',{}).get('hello')

# Numpy

In [35]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [36]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [38]:
arr=np.arange(20,36,2)
print(arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [39]:
mat =  np.arange(0, 9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [40]:
a = np.array([1,2,3])
b= np.array([4,5,6])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [41]:
import pandas as pd


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [42]:
pd.date_range(start='1/1/2023', end='1/02/2023')

DatetimeIndex(['2023-01-01', '2023-01-02'], dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [43]:
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]    
df = pd.DataFrame(lst,columns =['Tag','day','number']) 
print(df)

   Tag  day  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24
